.flowconfig, Gruntfile.js, README.md, package.json, playground.html, src/Controls.js, src/GenomeTrack.js, src/Root.js, src/TwoBit.js, src/main.js, src/types.js, types/types.js
Here it is in action:
Nothing too fancy, but it works!
There were a few Flow warts that I ran into:
- Flow can't track types through `this.props`—the `React.PropTypes` type system isn't precise enough.
- There's an [`import type`][1] statement coming very soon, but it won't import type aliases. "Soon", they say. For now, I'm putting shared type aliases in a global file.
This version of the code doesn't have much to say about how data will be organized eventually—thoughts on that would be much appreciated!
[1]: http://flowtype.org/blog/2015/02/18/Import-Types.html
=> Display the reference genome

.travis.yml, Gruntfile.js, package.json, scripts/post-coverage.sh, scripts/transform-coverage.js, test/RemoteFile-test.js, test/coverage.html, test/lcov-reporter.js
Fixes #5 
This wound up being an all-day odyssey. The gist of how it works is:
1. I strip types and browserify all the tests together, as before.
2. I split out the source map from the bundled file. This keeps it small (for faster execution & reporting) and makes the source map easier to access later.
3. I instrument the bundled tests using jscoverage. This instruments _all_ code, including node_modules. The line numbers it tracks are within the concatenated bundle.
4. I use a [modified][1] version of `mocha-lcov-reporter` with `mocha-phantomjs` to dump out LCOV data on the bundled JS file.
5. I run that through a new LCOV→LCOV script which applies the source map to get real line numbers.
Kinda messy, but it works!
[1]: https://github.com/StevenLooman/mocha-lcov-reporter/pull/7
=> Generate code coverage data

README.md, lib/underscore.js, scripts/post-coverage.sh, src/Controls.js, src/GenomeTrack.js, src/Root.js, src/TwoBit.js, src/main.js, src/types.js, types/types.js
It's quite flickery for now. I need to figure out a better story around only showing cached content while network requests are in flight.
=> Drag to pan genome

.flowconfig, src/ContigInterval.js, src/Interval.js, src/utils.js, test/ContigInterval-test.js, test/Interval-test.js, test/utils-test.js
New modules:
- `Interval` represents a closed numeric interval.
- `ContigInterval` represents a closed interval on the genome (i.e. a contig + an `Interval`).
- `utils` contains a few helpers for ordering tuples, ala Python.
All of these are well-tested. None of them are used right now, but they'll all be helpful for working with bigBed files.
=> Add Interval classes

Gruntfile.js, README.md
This reduces iteration time on the test bundle from 10–15s to around 1s.
Fixes #31
=> Faster rebuilds with watchify

lib/mocha.js, lib/underscore.js, package.json, playground.html, src/BigBedDataSource.js, src/Controls.js, src/GeneTrack.js, src/GenomeTrack.js, src/Interval.js, src/RemoteFile.js, src/Root.js, src/TwoBitDataSource.js, src/bedtools.js, src/main.js, test/BigBed-test.js, test/TwoBitDataSource-test.js, test/bedtools-test.js
The gist of this change is that we can now visualize genes:
A few other changes came along for the ride to facilitate this:
- Adds zoom in/out buttons (Fixes #29)
- Suppress reference track when sufficiently zoomed out (it's a crowded bottleneck)
- Adds a background to `GenomeTrack` to make it draggable even when not showing base pairs.
- Be more aggressive about pre-fetching the reference genome (smooths panning)
- Adds some tests to make sure network caching is working as expected.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/43)
=> Visualize genes

package.json
The pre-push hook gets installed when you run `npm install`.
Fixes #54 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/55)
=> Add prepush-hook for linting

playground.html, style/pileup.css, test/coverage.html, test/runner.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/56)
=> Factor out stylesheet

src/GeneTrack.js, style/pileup.css
Strand arrows are now visible over exons:
Strand arrows are aligned to the genome, so arrows on overlapping transcripts line up:
And overlapping labels are elided, ala IGV:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/58)
=> Improvements to gene display

src/RemoteFile.js, test/RemoteFile-test.js
- Adds `getAll()` and `getSize()` methods
- Rejects requests for non-existent files
- Better cache behavior at EOF
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/65)
=> RemoteFile improvements

src/bam.js, src/main.js, src/utils.js, test/bam-test.js, test/utils-test.js
This required a bit of refactoring. I ported over some more tests from htsjdk by stepping through them in IntelliJ.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/67)
=> Read BAM alignments across block boundaries

src/SamRead.js, src/bam.js, src/formats/bamTypes.js, test/SamRead-test.js, test/bam-test.js
This speeds up `BamFile.getAlignmentsInRange` in a few ways:
- Filters reads as it parses them to reduce memory overhead & bail out more quickly.
- Introduces a `SamRead` class for lazy parsing and type safety (Fixes #71)
- Reads `SamRead`s directly using `ArrayBuffer`, bypassing the jBinary overhead.
The latter optimization is particularly effective. Overall the "should fetch from a large, dense BAM file" test case went from taking ~1450ms/run on my machine to taking ~550ms/run.
See #26
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/74)
=> Optimize BAM parsing

src/SamRead.js, src/VirtualOffset.js, src/bam.js, test/SamRead-test.js, test/bam-test.js
This will allow de-duping them in `BamDataSource` after fetching.
This simplifies some code in `BamFile`.
See #26
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/75)
=> Attach VirtualOffsets to SamReads

lib/underscore.js, src/BamDataSource.js, src/BigBedDataSource.js, src/ContigInterval.js, src/Interval.js, src/TwoBitDataSource.js, test/BamDataSource-test.js, test/ContigInterval-test.js, test/Interval-test.js
Like the other data sources, this manages caching and speculative fetching, and creates an immediate, synchronous view over the remote data source.
This also adds `coalesce` and `isCoveredBy` methods to `Interval` and `ContigInterval` which facilitate working with collections of intervals.
See #26 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/79)
=> Add BamDataSource

lib/underscore.js, src/BamDataSource.js, src/PileupTrack.js, src/bam.js, src/pileuputils.js, style/pileup.css, test/BamDataSource-test.js, test/bam-test.js, test/pileuputils-test.js
It's starting to look like a real pileup viewer!
- Fix some issues around "chrX" vs. "X" as the ref name
- Implement a rudimentary pileup
- Tweak track style to match IGV
See #26
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/82)
=> Improvements to BAM visualization

src/GeneTrack.js, src/PileupTrack.js, src/bam.js, src/utils.js
Two improvements:
- Cache gzip block inflation (fixes #95)
This was slightly harder than expected, since inflating the same offset in a file can succeed or fail depending on how many bytes of the file have been read. This _is_ a win, though. During casual panning, the same block is inflated (successfully) 40+ times without it.
- Cache `offsetWidth` and `offsetHeight` calculations (fixes #94)
I was surprised to see these showing up in the flamecharts!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/98)
=> Performance improvements

src/GenomeTrack.js, style/pileup.css
Fixes #42 
There are four modes: Loose, Tight, Blocks and Hidden.
Loose:
Tight:
Blocks:
This is implemented by creating both `<text>` and `<rect>` elements for every base pair, one of which is hidden via CSS. It would be better to create just one or the other, but I wasn't quite sure what the right way to do this was in D3.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/107)
=> Change reference UI depending on scale

package.json, src/bam.js
This lets us use the new [`export type`][1] statement.
[1]: https://github.com/facebook/flow/issues/267#event-291051612
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/109)
=> Update to flow 0.10.0

src/PileupTrack.js, src/Root.js, src/SamRead.js, src/TwoBitDataSource.js, src/bam.js, src/pileuputils.js, style/pileup.css, test/BamDataSource-test.js, test/SamRead-test.js, test/TwoBitDataSource-test.js, test/pileuputils-test.js
First cut at this. Here's what it looks like:
What this does:
- Threads `referenceSource` through to `PileupTrack`
- Exposes a few more "fast" methods on `SamRead`, e.g. `getCigarOps` and `getSequence()`
- Uses the aligned length of a read for display, not the sequence length
- Factors out a `VisualAlignment` type for `PileupTrack` for data binding
- Uses a [nested selection][1] to indicate the mismatched bases
Still to do:
- Support indels and clipping
- Figure out why some reads are completely colored (off by one?)
- Re-color mismatches when the reference changes
- Scale the font of the mismatches in the same way as the reference track
See #84 
[1]: http://bost.ocks.org/mike/nest/
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
=> Indicate alignment mismatches

package.json, src/PileupTrack.js
Fixes #108 
This uses [ES6-style classes with React][1], which makes it easier to stick arbitrary fields (like a cache) onto a component without affecting `state` or `props`.
This is required for showing two pileup tracks (e.g. tumor and normal).
[1]: https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/119)
=> Update to React 0.13 and re-scope pileup cache

package.json, src/BigBedDataSource.js, src/GeneTrack.js, src/GenomeTrack.js, src/PileupTrack.js, src/Root.js, src/TwoBitDataSource.js, src/types.js
This takes most of the logic out of `Root.js`, which will facilitate creating a public-facing API.
See #30
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/121)
=> Pass data sources to visualizations

src/PileupTrack.js
PileupTrack now respects the size of its container and scrolls vertically to show the full pileup.
Fixes #87 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/126)
=> Adjustable Pileup Height

package.json, src/TwoBit.js, src/TwoBitDataSource.js, src/bam.js, src/formats/helpers.js, src/pileuputils.js, test/TwoBit-test.js, test/TwoBitDataSource-test.js
Previously it fired in response to every `rangeChanged` notification. Now it only fires when new data comes in. This should make it easier to address #115.
This also modifies the `TwoBit` interface to take a `RemoteFile` instead of a URL (for easier swapping of alternate implementations for testing). I updated to Flow 0.11 to get better error messages out of this, which also required a few changes. Neither of these was necessary, but they both seem like good ideas.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/141)
=> Eliminate over-firing of TwoBitDataSource.newdata

src/PileupTrack.js, src/Root.js, src/TwoBitDataSource.js, src/utils.js, test/PileupTrack-test.js, test/TwoBit-test.js, test/TwoBitDataSource-test.js, test/utils-test.js
- Sneaky `pos` vs. `position` error in the D3 key that was causing chaos.
- Ignore `initialRange` if `setRange` has already been called.
- Tolerate chr prefix mismatches between `rangeChanged` and `getRange` in `TwoBitDataSource`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/144)
=> A few more fixes for CycleDash

src/Controls.js, test/GenomeTrack-test.js
Fixes #148 
The test isn't actually a regression test—the bug was that clicking the zoom button triggered a form submit, a behavior which doesn't happen when I use React's TestUtils to click the button.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/149)
=> Restore zoom in/out buttons

package.json, scripts/post-coverage.sh
See #151 
This is a workaround until `grunt-exorcist` updates its `exorcist` dep.
It also works around https://github.com/cainus/node-coveralls/issues/80
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/152)
=> Pin grunt-browserify version

src/BamDataSource.js
Fixes #138
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/158)
=> Use index chunks in pileup.formats.bam

package.json
The production task was failing due to missing module, watchify:
```
$ grunt prod
Loading "browserify.js" tasks...ERROR
>> Error: Cannot find module 'watchify'
Warning: Task "browserify:dist" not found. Use --force to continue.
Aborted due to warnings.
```
Added watchify `^3.2.1` to the devDependencies to resolve this problem.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/162)
=> Production fails due to missing dependency

README.md
A quick fix to the URL in the README file to point to the right repository.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/164)
=> URL in the README now points to the hammerlab repo

package.json
When installing the package, NPM was complaining about the license:
```
$ npm install
npm WARN package.json pileup@0.1.0 license should be a valid SPDX license expression
```
Changed the license description to `Apache-2.0`, for SPDX compatibility.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/174)
=> License identifier is now a valid SPDX expression

Gruntfile.js, package.json
The earlier configuration in `package.json` was confusing  [node-browserify](https://github.com/substack/node-browserify), forcing it to re-browserify `build/pileup.js` and therefore causing it to fail. As an example, see the output of [this browserify request](https://wzrd.in/bundle/pileup@0.1.2) for our version `v0.1.2`:
```
---FLAGRANT SYSTEM ERROR---
(logs uuid: 48fd78d0-1074-11e5-8345-05735e43db5c )
Error: "browserify exited with code 1"
code: 1
stderr: Error: Cannot find module './lib/utils/common' from '/tmp/pileup115511-14891-13ix8yo/node_modules/pileup/build'
at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:42:25
at load (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/ …
```
=> Allow browserification via the standalone tool

examples/dalliance.html
Now that we're using pileup.js on Cycledash, we don't have a reference for how dalliance renders BAM tracks. This adds one for comparison.
cc @jaclynperrone
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/178)
=> Add a demo using BioDalliance

test/GenomeTrack-test.js, test/PileupTrack-test.js, test/components-test.js
A problem with the `watchify` was causing all relative requires turn into requires with full paths when initiated with `{ watch: true }` option; but due to our recent changes, the correct way to require our main module is now `require('pileup')`.
More info:
- https://github.com/jmreidy/grunt-browserify/issues/245
- https://github.com/jmreidy/grunt-browserify/issues/197
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/191)
=> Correct the way we require 'pileup' in tests

examples/playground-complete.html, examples/playground.js, src/Controls.js, src/GeneTrack.js, src/GenomeTrack.js, src/PileupTrack.js, src/Root.js, src/VariantTrack.js, src/types.js, style/pileup.css, test/components-test.js
Here's what it looks like:
This reworks `pileup.css` to use flexbox, which worked very well in Cycledash. You can see the shell of the layout in [this codepen][1].
@jaclynperrone any design feedback would be much appreciated here!
Fixes #129 
[1]: http://codepen.io/anon/pen/VLzbBe?editors=110
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/195)
=> Add track names

package.json
andreypopp merged [my PR][1], so we're safe to go back to the mainstream release.
[1]: https://github.com/andreypopp/jstransformify/pull/6
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/196)
=> Switch to mainstream jstransformify

src/BigBed.js
I'm surprised that this works with no errors, but I'm not complaining.
This _used_ to fail, but maybe something changed over the last five or six flow releases.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/201)
=> Strong flow on BigBed.js

src/BigBedDataSource.js, src/bai.js, src/bam.js, src/types.js, src/utils.js
For now, types shared between modules can live in `types.js`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/202)
=> Reduce type definition duplication

src/PileupTrack.js, src/bam.js, src/utils.js, test/BamDataSource-test.js, test/bam-test.js
Fetching the BAI file can be a significant part of the load time for pileup tracks, especially if there are no index chunks available. This will give more immediate feedback to the user that activity is happening.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/203)
=> Fire progress events for BAI fetching

src/Controls.js, style/pileup.css, test/GenomeTrack-test.js
This commit does a few things for the control button styles:
1. Changes `class` to `className` in `Controls.js`
2. Adds test to look for `.zoom-controls` div
3. Fixes css to display styles correctly
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/206)
=> Add test and fix js/css for control buttons.

.flowconfig, package.json
At least I'm pretty sure it's unused!
This is our only remaining forked dependency.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/212)
=> Drop unused reactify dep

README.md, package.json
With this, people have to
```
npm install
npm run build  # or npm run prod
```
for jstransform, browserify and uglify tasks.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/213)
=> Development-specific tasks are not part of the default install task any more

.travis.yml
We're not actually running the tests on Travis right now. mocha-phantomjs just says "0/0 passed", which counts as success:
https://travis-ci.org/hammerlab/pileup.js/builds/69762743
This is one thing we lose by dropping Grunt -- we need to track dependencies between build steps in some other way.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/217)
=> Run build before running test

.travis.yml, package.json, scripts/generate-coverage.sh, src/test/coverage.html
Istanbul instruments our source code with a coverage-tracking variable. This works great now that we have transformed files in `/dist`. I instrument each file individually and then browserify it to get accurate line numbers for coverage.
Fixes #209
Fixes #151
Closes #12 (that script is no longer needed)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/218)
=> Generate coverage data using Istanbul

examples/playground-complete.html, package.json
This should help us keep track of frame rates as we add features/optimizations. It seems to correlate well with how things feel as I pan back and forth. If I zoom out a few times and pan, I can see the frame rate drop to 1 or 2 fps.
If you click the meter, it switches between ms/frame and fps mode.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/220)
=> Add an FPS meter to playground-complete.html

src/main/BamDataSource.js, src/main/Root.js, src/main/bam.js
Previously, when a BAI file didn't have index chunks, any requests for the BAM file header would block on downloading the entire BAI file (which is required to know how precisely large the BAM header is). This meant that there would be no status message visible while the BAI file was being loaded.
This change shows a message when that's the case, so that you always get an immediate notification. I tried to thread this notification through `bam.js` but had no luck.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/224)
=> Show BAI fetch notification w/o index chunks

.travis.yml, package.json, scripts/generate-coverage.sh, scripts/post-coverage.sh, scripts/test.sh
- I noticed that whenever I ran `npm run test`, it left an http server behind. Switching from `pkill` to `kill` seems to fix that.
- The test script runs on its own port to avoid conflicting with a dev server you might already have running.
- I killed the `npm run mocha-phantomjs` task, since it was so heavily tied to `scripts/test.sh` anyway.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/222)
=> Tweaks to the test script

src/main/GenomeTrack.js, style/pileup.css
Previously a `<rect>` and a `<text>` element were created for every base pair and one was hidden via CSS. Now I only create one. The trick is to add a wrapper element whose d3 data is the display mode. That way it will handle cleanup for us via `enter()`/`exit()`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/223)
=> Clean up GenomeTrack base pair rendering.

src/main/pileuputils.js, src/test/pileuputils-test.js
If the reference isn't available yet, then we shouldn't color mismatches based on it. This should eliminate the flash of color you occasionally see in the pileup tracks on the demo.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/227)
=> Fix the flash of mismatches on initial load

src/main/DisplayMode.js, src/main/GenomeTrack.js, src/main/PileupTrack.js
Fixes #42 
This uses the same trick as `GenomeTrack`, i.e. creating a one-element wrapper to force updates when the display mode changes. There were enough differences between the two (one is a subselect, the other isn't; they use different coordinate systems) that I didn't think it was worth factoring out the commonalities.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/228)
=> Show mismatches as blocks when appropriate

lib/mocha.js, src/main/Alignment.js, src/main/BamDataSource.js, src/main/GA4GHAlignment.js, src/main/GA4GHDataSource.js, src/main/PileupTrack.js, src/main/SamRead.js, src/main/pileup.js, src/test/GA4GHAlignment-test.js, src/test/GA4GHDataSource-test.js, test-data/README.md, test-data/chr17.1-250.json
As demoed last Friday.
Highlights:
- I factored out a common interface for alignments, shared between BAM & GA4GH sources.
- GA4GHDataSource is currently untested. I'm thinking about how to best remedy that.
- The BAM↔GA4GH equivalency test surfaced many issues with the GA4GH server.
- This isn't surfaced via the playground example. I'm not sure how it could be (you'd have to run a GA4GH server). Maybe there's a public one running that we could point to.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/230)
=> GA4GH data source

examples/playground.js, src/main/CoverageTrack.js, src/main/GA4GHDataSource.js, src/main/GeneTrack.js, src/main/GenomeTrack.js, src/main/PileupTrack.js, src/main/d3utils.js, src/main/pileup.js, src/main/utils.js, src/test/CoverageTrack-test.js, style/pileup.css
This is a new track implementation that uses BAM format as input and plots a histogram-like graph that shows how many reads overlap with each nucleotide within the visible range. If the range changes (zoom in/out or panning), it adjusts the size of the bars and the information shown on the Y axis accordingly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/229)
=> Display coverage information for BAM sources

package.json
The newer version of the `mocha-phantomjs` (v3.6.0) requires an older version of phantomjs and this create a dependency conflict, causing [our build to fail](https://travis-ci.org/hammerlab/pileup.js/builds/71798433). This change fixes the version of our `mocha-phantomjs` dependency to resolve that issue.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/236)
=> Fix the version for mocha-phantomjs dependency

src/main/BamDataSource.js, src/main/ContigInterval.js, src/main/CoverageTrack.js, src/main/GA4GHDataSource.js, src/main/PileupTrack.js, src/test/CoverageTrack-test.js
This makes `BamDataSource`'s `newdata` event fire only when new data becomes available (previously it fired when a cached region was requested, too). This should significantly reduce re-computation in `PileupTrack`.
I also reworked the data flow in `CoverageTrack` so that it only computes summary statistics when `newdata` fires.
Performance numbers while panning on the playground demo:
Before: 4-5fps
After: 9-10fps
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/232)
=> Optimizations for alignment tracks

src/main/CoverageTrack.js, src/main/GeneTrack.js, src/main/GenomeTrack.js, src/main/PileupTrack.js, src/main/Root.js, src/main/VariantTrack.js, src/main/VisualizationWrapper.js, src/main/types.js
This eliminates two sources of duplicated code:
- The empty / non-empty track dance that each component had to do. This is now done by a new component, `VisualizationWrapper`.
- Caching the track's size. The last-measured size is passed down via `props.{width,height}` now.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/237)
=> Consolidate duplicated code across Visualization tracks

examples/playground.js, src/main/CoverageTrack.js, src/main/EmptySource.js, src/main/LocationTrack.js, src/main/Root.js, src/main/ScaleTrack.js, src/main/d3utils.js, src/main/pileup.js, src/main/utils.js, src/test/components-test.js, src/test/d3utils-test.js, src/test/utils-test.js, style/pileup.css
This implements two tracks that do not use data sources, but create helper visualizations based on the visible genomic range (closes #62).
`LocationTrack` marks the middle of the visible range and shows the exact base location next to the line mark:
`ScaleTrack` track includes a centered scale bar of which size is determined by the visible range and a `niceify` method that heuristically fine tunes the exact size of the bar. For regions bigger than 1000bp, the visualization creates a scale bar on the order of kilobase (kb), megabase (mb) or gigabase (gb):
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/241)
=> Add support for location and scale tracks

.flowconfig, lib/q.js, lib/underscore.js, package.json, src/main/Alignment.js, src/main/CoverageTrack.js, src/main/GA4GHDataSource.js, src/main/PileupTrack.js
See [FlowType changelog][1].
I've also taken the opportunity to re-enable type checking for underscore. This lets many types flow through which didn't before & exposed a few existing errors. Type inference seems to have gotten significantly better!
[1]: https://github.com/facebook/flow/blob/master/Changelog.md#v0150
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/247)
=> Update to flow 0.15

examples/playground.js, lib/underscore.js, src/main/PileupCache.js, src/main/PileupTrack.js, src/main/Root.js, src/main/SamRead.js, src/main/TwoBitDataSource.js, src/main/pileuputils.js, src/test/PileupCache-test.js, style/pileup.css
This factors out a PileupCache class, which manages the data being visualized by PileupTrack.
Here's what it looks like:
Remaining work, probably for follow-up PRs:
- Make "view as pairs" optional (includes some design & API work, too)
- Performance optimizations (there seems to be a bit of a regression)
- Pack the reads more intelligently (there's more wasted space now)
Fixes #110 
Fixes #108
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/251)
=> Show paired reads in PileupTrack.

package.json, scripts/lint.sh, src/main/Alignment.js, src/main/PileupCache.js, src/main/PileupTrack.js, src/main/VariantTrack.js, src/main/VcfDataSource.js, src/main/bedtools.js, src/main/data-canvas.js, src/main/pileuputils.js, src/main/vcf.js, src/test/PileupTrack-test.js, src/test/components-test.js, src/test/data-canvas-test.js, src/test/pileuputils-test.js, types/types.js
See #255 
When I remove all tracks but a single `PileupTrack`, I see panning performance at ~700bp scale go from ~20fps→60fps. It's better than that, though. The SVG version sometimes goes down to around 6fps while panning, whereas the canvas version never drops below 30fps.
Remaining bits to implement:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/257)
=> Migrate PileupTrack from SVG→canvas

src/main/BigBedDataSource.js, src/main/GeneTrack.js, src/main/data-canvas.js, src/test/BigBed-test.js, src/test/GeneTrack-test.js, src/test/data-canvas-test.js
See #255 
This fixes a few style issues:
- Render intron arrows in blue
- Draw correct strand arrows
It also adds `GeneTrack-test` and fixes a bug this exposed in `RecordingContext`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/263)
=> Gene fixup

src/main/GenomeTrack.js, src/main/VisualizationWrapper.js, style/pileup.css
I moved the drag-to-pan functionality into `VisualizationWrapper`, so that it's automatic for all tracks. Clicks still fall through for the track itself to handle.
Fixes #61 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/264)
=> Make all tracks draggable!

examples/playground-complete.html, examples/playground.js, src/main/pileup.js
Or at least semi-automated, you still have to click a button:
This should be slightly more reliable than the approach we've used so far (wildly dragging around with the mouse and watching the FPS meter).
Also adds a defensive copy to `pileup.getRange`, so that users can't accidentally muck with its internal React `state`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/267)
=> Add an automated speed test

src/main/CoverageTrack.js, src/main/style.js, src/test/CoverageTrack-test.js
Rendering with canvas:
See #255 
The labels used to be much sharper and they look uglier on the canvas, but hopefully #261 will solve this issue once and for all.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/266)
=> Migrate Coverage from SVG→canvas

src/main/data-canvas.js, src/test/data-canvas-test.js
See #278 
This seems to be a small performance win.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/279)
=> Cache calls to getDataContext

src/main/CoverageTrack.js, src/main/GeneTrack.js, src/main/GenomeTrack.js, src/main/LocationTrack.js, src/main/PileupTrack.js, src/main/ScaleTrack.js, src/main/VariantTrack.js, src/main/d3utils.js, src/test/CoverageTrack-test.js, src/test/PileupTrack-test.js, src/test/d3utils-test.js
This removes calls to `d3.select`
See #275
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/281)
=> Start reducing d3 dependencies

src/main/VariantTrack.js
Previously it ignored height/width changes.
Fixes #253
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/283)
=> Update VariantTrack on any prop/state change.

src/main/CoverageTrack.js, src/main/GeneTrack.js, src/main/GenomeTrack.js, src/main/LocationTrack.js, src/main/PileupTrack.js, src/main/ScaleTrack.js, src/main/VariantTrack.js, src/main/d3utils.js
Fixes #261 
See [this article][1]. The bit about `backingStoreRatio` seems to be out-of-date. I tested this in Firefox & Chrome.
[1]: http://www.html5rocks.com/en/tutorials/canvas/hidpi/
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/285)
=> Support retina displays

scripts/generate-coverage.sh
The Istanbul HTML report shows other types of coverage, e.g. function, branch and statement coverage (Coveralls only reports line coverage). It shows them for the transpiled JS, which is not ideal, but you can usually get a pretty good idea of what's going on!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/290)
=> Generate HTML coverage locally

lib/underscore.js, src/main/pileup.js, src/main/types.js, src/test/components-test.js
The issue was that I was calling `_.findWhere`, which expects key-value pairs to look for, rather than `_.find`, which takes a predicate.
Why Flow didn't catch this is beyond me.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/303)
=> Allow any track to be the reference

src/main/BigBed.js, src/main/utils.js
I noticed that pako was split between inflate & deflate in the treemap earlier today. We only use inflate, so there's no need to depend on the deflate code. Fortunately, pako makes this easy.
475353 pileup.min.js before
452646 pileup.min.js after
i.e. a 22k = 5% space savings.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/305)
=> Only depend on pako/inflate

package.json
To facilitate debugging bundle size with source-map-explorer
The net result here is that we get two new files in `dist`:
```
dist/pileup.js.map
dist/pileup.min.js.map
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/309)
=> Generate a source map for pileup.min.js

package.json, scripts/make-mini-d3.sh, src/main/CoverageTrack.js, src/main/GeneTrack.js, src/main/LocationTrack.js, src/main/PileupTrack.js, src/main/d3utils.js, src/main/pileup.js, src/main/scale.js, src/test/coverage.html, src/test/d3utils-test.js, src/test/runner.html, src/test/scale-test.js
See #275 
This gets minid3 down to ~15k in the minified bundle, just the bit contributed by `d3.behavior.drag`.
After trying to update cycledash to use the latest pileup, I realized there was a problem. The directory structure looks like this:
```
cycledash
node_modules
d3
pileup
node_modules
...
```
The `make-mini-d3.sh` script expects its copy of D3 to be in `pileup/node_modules`, but if the parent project depends on d3 itself, then there's no reason to expect that this will be the case.
If we want to get the benefit of not depending on all of d3, then we need to either sever the dependency completely or distribute a copy of minid3 outside of `node_modules`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
=> Sever dependence on d3.{scale,format}

src/main/RemoteFile.js, src/test/RemoteFile-test.js
I was seeing a lot of this in Cycledash:
This should help clarify what's going on.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/323)
=> Mention the URL in Request failed errors

.flowconfig, src/main/Controls.js, src/main/PileupTrack.js, src/main/utils.js, src/test/utils-test.js
These popped up when I tried updating pileup in Cycledash.
With the `scaleRange` change, we lose the invariant that the range is precisely half or double what it was before, but we gain an invariant that the center base stays fixed, which is what you notice most easily.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/322)
=> Fix two small bugs

.gitignore, scripts/post-coverage.sh, scripts/post_code_size.py
We build the minified file anyway, so we may as well track it!
Notes:
- This is intentionally dependency-free. Running Python in the node Travis-CI stack is messy. I was unable to get `pip install requests` to work.
- I'll add support for changes in size once we have this running on `master`. My plan is to use the GitHub API to figure out the base for the current PR, then fetch and parse its build status.
- I had to add a `GITHUB_TOKEN` environment variable to our Travis build. I got this using Profile→Settings→Personal Access Tokens on GitHub.
References:
- [GitHub Notifications API][1]
- [Unanswered question][2] about this on StackOverflow
- [urllib2 documentation][3]
- [Travis-CI environment variables][4]
[1]: https://developer.github.com/v3/repos/statuses/
[2]: …
=> Attempt to notify on code size

.travis.yml, scripts/post-coverage.sh, scripts/post_code_size.py
This builds on #327 
This is a bit roundabout because of how Travis-CI handles pull requests. As near as I can tell:
- When you push anything to GitHub, Travis-CI starts a "push" build. This has the `TRAVIS_COMMIT` environment variable set, but not `TRAVIS_PULL_REQUEST`. This makes sense, since the push might not be part of a PR.
- When you create a pull request for a branch, Travis-CI starts a "pr" build. This checks out something like `refs/pull/328/merge`, which is the PR branch as merged onto whatever its base is. This has, e.g. `TRAVIS_PULL_REQUEST=328`, and `TRAVIS_COMMIT` set to whatever the merge commit's SHA is.
- GitHub only shows statuses for the "push" commit in the PR view.
It's difficult to determine PR information in the "push" build (see [this question][1]), so instead I …
=> Attempt to display deltas

src/main/PileupTrack.js
This was breaking Cycledash.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/329)
=> Be very careful about testing for setLineDash

scripts/build.sh, scripts/post-coverage.sh
Fixes #330 
Compare `RemoteFile.js` coverage [before][] and [after][]. The latter makes sense, the former does not.
[before]: https://coveralls.io/builds/3932994/source?filename=src%2Fmain%2FRemoteFile.js
[after]: https://coveralls.io/builds/3953163/source?filename=src%2Fmain%2FRemoteFile.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/331)
=> Retain lines when running babel

src/main/CoverageTrack.js, src/main/style.js
This includes a bunch of changes:
1. eliminates the Moiré pattern (fixes #334). This required splitting out the mismatch rendering code into a separate loop.
1. rounds the y-axis coordinates to get crisper rendering. IGV.js does this and it looks much nicer.
1. fixes a bug where the bars were all ~10px too high, thus giving incorrect counts. Funny that we never noticed this!
1. restored the white border on the coverage track scale. I believe this was lost in the SVG→canvas transition (we used to do it with CSS).
Here's a before/after:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/338)
=> Visual improvements to CoverageTrack

.flowconfig, README.md, lib/underscore.js, package.json, scripts/test.sh, src/main/ContigInterval.js, src/main/Interval.js, src/main/PileupTrack.js, src/main/RemoteFile.js, src/main/TiledCanvas.js, src/main/utils.js, src/test/TiledCanvas-test.js, src/test/components-test.js, src/test/utils-test.js
Fixes #86 
This introduces `TiledCanvas`, which maintains a cache of previously rendered buffers. This greatly improves performance during panning, since each frame just involves drawing pre-rendered buffers on the on-screen canvas. Panning at any zoom level improves to ~60fps after this change.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/346)
=> Tiled Canvas

package.json, src/main/ContigInterval.js, src/main/CoverageTrack.js, src/test/CoverageTrack-test.js
See #351
Adding explicit types for props/state works really nicely. It makes Flow much more useful for these components.
The hack for PhantomJS is kinda gross, but I don't see an alternative.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/353)
=> Tile the CoverageTrack

.flowconfig, package.json, src/main/Alignment.js, src/main/BigBedDataSource.js, src/main/Controls.js, src/main/GeneTrack.js, src/main/GenomeTrack.js, src/main/LocationTrack.js, src/main/PileupTrack.js, src/main/Root.js, src/main/ScaleTrack.js, src/main/TwoBitDataSource.js, src/main/VariantTrack.js, src/main/VisualizationWrapper.js, src/main/d3utils.js, src/main/pileup.js, src/main/types.js
Fixes #235 
This migrates all React components to use ES6 classes and declares types for `state` and `props` in all of them. This should make Flow much more effective.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/354)
=> Props states types

lib/underscore.js, src/main/PileupCache.js, src/main/PileupTrack.js, src/test/PileupCache-test.js
See #181 
There's no UI for this yet. I'm thinking of two ideas there:
1. When you go to a new location (either on the initial load or by jumping to a previously unloaded region), then the alignments should get sorted around the center position.
1. There could be an option to sort the reads via the UI, maybe under a gear icon below the pileup track label.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/355)
=> Implement PileupCache.sortReadsAt

src/main/GenomeTrack.js, src/main/PileupTrack.js, src/main/TiledCanvas.js
This is an easy win. Getting it right for `CoverageTrack` is going to be a little trickier, since new data could change the y-axis range.
See #375 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/376)
=> Add TiledCanvas.invalidateRange

style/pileup.css
Looks like [the mysterious-vertical-space bug](https://github.com/hammerlab/cycledash/pull/811) is at it again: http://www.hammerlab.org/pileup/
This removes the default white space around `canvas` elements and fixes the problem.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/377)
=> Remove white space around canvas items

src/main/Alignment.js, src/main/BamDataSource.js, src/main/ContigInterval.js, src/main/GA4GHDataSource.js, src/main/TwoBitDataSource.js, src/test/BamDataSource-test.js, src/test/ContigInterval-test.js, src/test/TwoBitDataSource-test.js
Fixes #379 
This is a _really_ nice performance win. See explanation in issue #379. After this, panning at 16,000bp resolution is pretty reasonable.
There were no screenshot diffs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/381)
=> Only fetch new ranges in {TwoBit,Bam}DataSource

src/main/PileupTrack.js, src/main/d3utils.js
The issue is that one of the pileups winds up with `scrollLeft=15`. I'm not sure why. It only happens in Chrome.
You can still see the issue after this change while you're panning, but it goes away once you let go of the mouse.
Mitigates #350
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/383)
=> Force pileup tracks to stay aligned

scripts/build.sh, scripts/lint.sh, src/main/pileup.js
This will be helpful if we ever want to check what version of pileup someone is using, e.g. ourselves on hammerlab.org or someone else on dnanexus.
Nothing ever stays in sync unless you force it to, so I've added a lint check that the two version numbers are the same.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/388)
=> Record version in pileup.version

src/main/TiledCanvas.js
Fixes #384 
The issue was that the track height would increase (because the pileup got taller due to added reads) and the existing tiles would be stretched vertically to match it. This was goofy. Tiles should be rendered at their natural height.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/392)
=> Don't stretch tiles vertically

package.json, src/main/GA4GHAlignment.js, src/main/VisualizationWrapper.js, src/main/data/formats/helpers.js, src/main/viz/CoverageCache.js, src/main/viz/CoverageTrack.js, src/main/viz/GeneTrack.js, src/main/viz/GenomeTrack.js, src/main/viz/LocationTrack.js, src/main/viz/PileupTrack.js, src/main/viz/ScaleTrack.js, src/main/viz/VariantTrack.js, src/main/viz/d3utils.js
See their [changelog][1]. The only really interesting thing here is the bug it uncovered in `GA4GHAlignment.js`.
[1]: https://github.com/facebook/flow/releases/tag/v0.20.0
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/400)
=> Update to Flow 0.20

.travis.yml, src/main/data/bai.js
For reasons unknown to me, some BAI files seem to have contigs of size 0. This was forcing pileup.js to try to fetch `Infinity` bytes and eventually fail. This change captures the edge case and caps the chunk size as a fix to issue #405 and #406.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/407)
=> Better handle BAI chunk sizes (fixes #405 and #406)

src/main/sources/TwoBitDataSource.js, src/test/sources/TwoBitDataSource-test.js, src/test/viz/GenomeTrack-test.js
This pull request is a patch that fixes bug reported here: https://github.com/hammerlab/pileup.js/issues/416
Here is brief description of the bug source:
When TwoBitDataSource object was requested to obtain data from huge range it checked if the region was already fetched ('covered') from remote file. If the chunk wasn't fetched from remote file it marked the region as fetched and then tried to fetch it. However, in the fetch method there was additional check that compared the requested range size with maximum allowed fetch range size. When request was too big it silently skipped fetching.
I moved "marking regions as covered" after range size checks.
I provided two test cases for the bug:
* low level unit test for TwoBitDataSource which shows the flow in patched file
* test case that …
=> Devel genome track bug

src/main/VisualizationWrapper.js
This small pull request fixes issue that I reported here: https://github.com/hammerlab/pileup.js/issues/415
During pileup destroy call, listener added by VisualizationWrapper at initialization stage is removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/418)
=> Fix on cleaning during destroy method

src/main/sources/BigBedDataSource.js, src/main/viz/GeneTrack.js
Here is a patch that fixes https://github.com/hammerlab/pileup.js/issues/417 issue.
Short desription of the problem:
When passing information between GeneTrack and BigBedDataSource at some point intervals were mixed up (interval that was requested, and interval for which data was obtained). This resulted in skipping data that didn't match to both of the intervals.
@armish I mentioned more pull requests. This is the last for now. I plan to do at least one more (add onclick events on variants), but I don't have time now. Hopefully I will get back to it in late July.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/422)
=> Fix of the gene-track zoom issue

src/main/AbstractFile.js, src/main/LocalStringFile.js, src/main/RemoteFile.js, src/main/data/vcf.js, src/main/sources/VcfDataSource.js, src/test/LocalStringFile-test.js, src/test/data/vcf-test.js
This pull request contains simple functionality that allows to visualize vcf files that were dynamically created in memory by javascript code.
Ideally it would be great to have possibility to create dynamic content for variant track. Here I provide a simple tool that allows it to some extend. When creating variant track there is possibility to intialize it with the content of vcf file instead of url. 
Of course it should be used for small dynamic content.
Some technical comments:
* I implemented LocalStringFile that has the same interface as RemoteFile. This class is initialized with content of the file in a String
* There is "abstract" class that is a super class for LocalStringFile and RemoteFile. However, due to some lint and facebook/flow restrictions implementation of this class is …
=> Dynamically generated vcf content

src/main/Root.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/426)
=> Disabled scrolling to negative regions

src/main/Interval.js, src/test/Interval-test.js
Fixed isCoveredBy() to pass for cases where the interval is not found in the first Interval queried
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/450)
=> Interval.isCoveredBy() fix

src/main/viz/CoverageTrack.js
Before
After
Resolve #439
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/455)
=> Coverage fix

style/pileup.css
There has been an issue with long label names, shown here:
The fix shows ellipsis for long labels but allows you to hover to get the full name.
Without hover (Variants label):
With hover (Variants label):
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/458)
=> fixed label overflow issue

src/main/json/GA4GHJson.js, src/main/pileup.js, src/test/json/GA4GHJson-test.js
This is primarily to allow pileup.js to be used in platforms other than the browser. For example, a user can load data into a pandas data frame in python, and pipe the dataframe using the  to_json() function into pileup. Since python notebook supports html and JS, one can immediately view their in the same environment. 
I think I will eventually add similar functionality for variants, features, etc. but thought this is a good starting point for discussion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/460)
=> Added GA4GHAlignments to be accessible through raw json

style/pileup.css
Follow up of #463
This change will set minimum height values for tracks to help prevent the use case where the window is too small to view anything, shown below
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/465)
=> Set minimum size for track viewing

examples/data-ga4gh.js, src/main/ContigInterval.js, src/main/sources/GA4GHAlignmentSource.js, src/main/sources/GA4GHVariantSource.js, src/main/sources/VcfDataSource.js, src/main/viz/FeatureTrack.js, src/main/viz/GeneTrack.js, src/main/viz/PileupCache.js, src/main/viz/TiledCanvas.js, src/test/sources/GA4GHAlignmentSource-test.js, src/test/sources/GA4GHVariantSource-test.js
This removes the requirement for specifying 'killChr' in the demos. Now, there are no issues with 'chr1' vs '1' in the reference vs data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/471)
=> removed 'killChr' requirement for demos

src/main/sources/GA4GHAlignmentSource.js
This is an issue if spec.forceReferenceId is not set
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/473)
=> fixed check for forced referenceId in GA4GH examples

scripts/test.sh
After changing pythonjs to mocha-headless-chrome there was no way to run single test from the console. 
For instance this call executed all unit tests, but shouldn't.
```
npm run test -- --grep=pileuputils
```
This PR restores grep functionality when running unit tests.
=> after changing pythonjs to mocha-headless-chrome grep on unit tests stopped working

src/main/viz/GenotypeTrack.js
addresses https://github.com/hammerlab/pileup.js/issues/530
=> fixed genotype track to not display 0,0 calls

lib/underscore.js, src/main/Controls.js, src/main/Root.js, src/main/data/TwoBit.js, src/main/sources/TwoBitDataSource.js, src/main/viz/GeneTrack.js, src/test/FakeAlignment.js, src/test/FakeTwoBit.js, src/test/components-test.js, src/test/data/TwoBit-test.js, src/test/sources/TwoBitDataSource-test.js, src/test/viz/FeatureTrack-test.js, src/test/viz/GeneTrack-test.js, src/test/viz/GenotypeTrack-test.js, src/test/viz/PileupTrack-test.js, src/test/viz/VariantTrack-test.js, style/pileup.css
Previously, the browser could scroll past the end of contigs. We now grab the number of bases from the current contig being viewed, and restrict viewing to this region. This required a substantial rebase of viz tests, that previously used a twobit file with short contigs. We now use a fake twobit file so all regions can be accessed during testing.
TODOs:
=> Don't let users view past the end of contigs

src/main/pileup.js
In recent react versions, ReactDOM.render() can return null and should not be relied on. We now use refs.
=> fixed null reactElement

src/main/viz/CoverageCache.js, src/main/viz/CoverageTrack.js, src/test/viz/CoverageCache-test.js, src/test/viz/CoverageTrack-test.js
There were two issues with coverage:
1. bars were being rendering incorrectly when there were undefined bins before a bar
2. max coverage was set to the max of the whole chromosome, making it hard to see coverage in regions with low coverage
=> Coverage rendering and maxCoverage

src/main/data/vcf.js, src/test/data/vcf-test.js, test-data/snv-chr-prefix.vcf
This PR address small issue with mapping chromosomes ids to numbers. When vcf file contained chromosomes like `chr20` the id was mapped to `0` instead of `20`.
There is also a unit test showing the issue.
=> problem with chromosome mapping in vcf
