- .travis.yml
> Configure Travis-CI

- .flowconfig
- Gruntfile.js
- package.json
- playground.html
- src/GenomeTrack.js
- src/main.js
No dragging/panning or anything fancy, but it's a start!
> Render colored base pairs using D3

- Gruntfile.js
- package.json
> Silence LCOV output

- Gruntfile.js
- README.md
- lib/underscore.js
- package.json
- playground.html
- src/GenomeTrack.js
- src/Root.js
- src/TwoBitDataSource.js
- src/main.js
- types/types.js
(compare to #19)
This mostly eliminates the flicker as you pan. There's still a little bit of jumpiness which I need to track down, but at least the whole genome doesn't flicker in and out of view.
The view component (`GenomeTrack`) no longer has to know anything about the network or async code.
I'm using Backbone for events. It definitely pulls in more stuff than we need, but it's a lightweight compared to D3 and React (20K vs. 148K and 127K).
[gif]: https://s3.amazonaws.com/f.cl.ly/items/0J3g111T0n3s2l250a05/Screen%20Recording%202015-03-05%20at%2005.35%20PM.gif
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/20)
> Mediate between backend & view with a cache layer.

- src/Controls.js
Based on https://github.com/danvk/react-inputs-toy.
> Allow editing the range via Controls

- src/bai.js
- src/bam.js
- test/RecordedRemoteFile.js
- test/bai-test.js
Adds `RecordedRemoteFile`, which should be handy for testing.
See #26  
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/70)
> Use index chunks in BaiFile

- src/SamRead.js
- src/bam.js
- test/SamRead-test.js
- test/bam-test.js
See #26
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/78)
> Add human-readable ref names to SamRead

- playground.html
- src/GeneTrack.js
- src/PileupTrack.js
- src/Root.js
- src/main.js
- style/pileup.css
- test/components-test.js
It's not much to look at yet, but pileup.js is finally rendering a pileup!
See #26
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/81)
> PileupTrack visualization

- test/BamDataSource-test.js
- test/BigBed-test.js
- test/BigBedDataSource-test.js
- test/ContigInterval-test.js
- test/Interval-test.js
- test/MappedRemoteFile-test.js
- test/RemoteFile-test.js
- test/SamRead-test.js
- test/TwoBit-test.js
- test/TwoBitDataSource-test.js
- test/VirtualOffset-test.js
- test/bai-test.js
- test/bam-test.js
- test/bedtools-test.js
- test/components-test.js
- test/helpers-test.js
- test/pileuputils-test.js
- test/utils-test.js
I recently learned that you can [return a Promise][1] from a Mocha test and it will handle everything for you—no `done` callbacks necessary.
@ihodes and @tavinathanson as an FYI next time you write async tests
[1]: http://stackoverflow.com/a/29831024/388951
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/93)
> Promisify tests

- src/PileupTrack.js
- src/SamRead.js
- src/TwoBitDataSource.js
- src/utils.js
- style/pileup.css
- test/bam-test.js
Looking like IGV:
Fixes #83
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/99)
> Show strand in BAM alignments

- src/PileupTrack.js
- src/main.js
- src/pileuputils.js
- test/pileuputils-test.js
Fixes #104 
While the pileups are stable, the layout is much looser. Adding many reads at once might be better.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/105)
> Stable pileups

- src/PileupTrack.js
- src/SamRead.js
- src/bam.js
- src/formats/bamTypes.js
- test/SamRead-test.js
- test/bam-test.js
See #103 
I got rid of any direct uses of `BamAlignment`. It's `SamRead` everywhere now.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/106)
> Display read.debugString() on click

- .gitignore
- src/ContigInterval.js
- src/RemoteFile.js
- src/Root.js
- src/VariantTrack.js
- src/VcfDataSource.js
- src/main.js
- src/vcf.js
- style/pileup.css
- test/ContigInterval-test.js
- test/RemoteFile-test.js
- test/VcfDataSource-test.js
- test/components-test.js
- test/data/snv.chr17.vcf
- test/data/snv.vcf
- test/vcf-test.js
Here's what it looks like for now:
This does pretty minimal parsing of the VCF file—just enough to do searches.
Fixes #25
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/116)
> Add support for VCF sources

- Gruntfile.js
- package.json
- src/BamDataSource.js
- src/BigBedDataSource.js
- src/Controls.js
- src/GeneTrack.js
- src/GenomeTrack.js
- src/PileupTrack.js
- src/TwoBitDataSource.js
- src/VariantTrack.js
- src/VcfDataSource.js
- src/main.js
- src/react-types.js
- src/types.js
- test/BamDataSource-test.js
- test/BigBedDataSource-test.js
- test/TwoBitDataSource-test.js
- test/VcfDataSource-test.js
- test/components-test.js
This switches pileup to jstransform, which is the new react-tools. This required a few upstream changes.
This is a first step on the way to #30
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/120)
> Refactor sources

- src/Root.js
- src/VariantTrack.js
- src/main.js
- test/components-test.js
Another move towards #30
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/122)
> Pass a track list to <Root/>

- src/BamDataSource.js
- src/BigBedDataSource.js
- src/Root.js
- src/TwoBitDataSource.js
- src/VcfDataSource.js
- src/main.js
- src/pileup.js
- src/types.js
- test/BamDataSource-test.js
- test/BigBedDataSource-test.js
- test/TwoBitDataSource-test.js
- test/VcfDataSource-test.js
- test/components-test.js
**WIP**
This is a first crack at #30 
See `main.js` for an example of what the API looks like as of this PR.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/123)
> High level API

- package.json
Fixes #127 
This shrinks ~600k off the minified JS bundle. Yikes!
See https://github.com/jDataView/jBinary/pull/43
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/128)
> Update to jBinary 2.1.3 for browserify

- src/Root.js
- src/main.js
- src/pileup.js
- test/components-test.js
I copied the name `setLocation` from Dalliance. I don't feel strongly about it, though, and I could be persuaded that there's a better name for it!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/124)
> Add {get,set}Location API methods

- package.json
- src/vcf.js
- test/data/sort-bug.vcf
- test/vcf-test.js
Software is hard.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/133)
> Fix & regression test for VCF sorting bug

- src/Controls.js
- src/GeneTrack.js
- src/GenomeTrack.js
- src/PileupTrack.js
- src/Root.js
- src/VariantTrack.js
- src/pileup.js
- src/react-shim.js
- src/react-types.js
- test/components-test.js
This allows pileup to be used in another application's react tree.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/135)
> Workaround for react/1939 + test

- src/GenomeTrack.js
- src/PileupTrack.js
- src/utils.js
- style/pileup.css
TIL: CSS class names are mostly case insensitive, [except when they're not][1].
[1]: http://stackoverflow.com/a/12533957/388951
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/140)
> Rework base pair CSS classes

- src/Root.js
- src/TwoBitDataSource.js
- test/GenomeTrack-test.js
- test/TwoBitDataSource-test.js
Fixes #146
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/147)
> chr-tolerance for setRange

- src/Controls.js
- src/GenomeTrack.js
- src/PileupTrack.js
- style/pileup.css
- test/GenomeTrack-test.js
- test/PileupTrack-test.js
Fixes #145
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/153)
> Center base pair text

- playground.html
- src/PileupTrack.js
- src/pileuputils.js
- style/pileup.css
- test/PileupTrack-test.js
- test/pileuputils-test.js
This also handles mismatches in the presence of more complex Cigar strings.
Fixes #85 
Fixes #111
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/157)
> Show Indels and Soft Clip alignments

- playground.html
- src/GeneTrack.js
- src/GenomeTrack.js
- src/PileupTrack.js
- src/VariantTrack.js
Fixes #139 
There's a lot of duplication here that I'd like to get rid of when creating a public visualization API.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/159)
> Track window resizes

- src/GenomeTrack.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/160)
> Show left-most base pair in reference

- playground.html
This resolves issue #163.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/167)
> Initialize pileup with URLs to the data hosted by biodallliance within playground.html

- package.json
- URLs are now pointing to the hammerlab repository fwiw
- New keywords related to genomics and sequencing for increased visibility
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/168)
> updated the URLs and added new keywords in package description

- src/BamDataSource.js
- src/PileupTrack.js
- src/bam.js
- src/types.js
- style/pileup.css
- test/BamDataSource-test.js
- test/bam-test.js
Not especially pretty, but it works!
Fixes #170
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/197)
> Show progress while loading pileups

- README.md
- Link off to the demo
- Add some usage documentation (both JS & CSS)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/198)
> Update documentation for blog post

- README.md
- src/Controls.js
- style/pileup.css
- test/GenomeTrack-test.js
This commit does a few things:
- Minor updates to README
- Adds classes to control buttons to make them more customizable across other projects
- Updates test to look for the zoom in/out button `className` instead of `textContent`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/199)
> Control classes

- .flowconfig
- test/GenomeTrack-test.js
- test/PileupTrack-test.js
- test/components-test.js
Fixes #200 
We don't care much about these errors, so we may as well suppress them while we work on a better solution.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/204)
> Hacky workaround for #200

- package.json
- scripts/publish.sh
This gets the `dist` directory into a good state for publication on npm.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/214)
> publish script

- examples/playground.js
- src/main/PileupTrack.js
- style/pileup.css
This commit does a couple things:
- Closes #208 
- Styles loading indicator
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/216)
> Style fixes

- src/main/PileupTrack.js
- src/main/SamRead.js
- src/main/pileuputils.js
- src/test/pileuputils-test.js
Fixes #155
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/225)
> Tie mismatch opacity to read quality

- src/main/BamDataSource.js
This change marks an interval as "covered" immediately after it's requested. This has the effect of preventing duplicate requests.
For example, if you were panning to the right, `BamDataSource` would repeatedly fetch the same interval until it got data back (and marked it as covered). Now it just fetches it once.
This is a pretty nice win. With all four pileup+coverage tracks, panning is noticeably smoother.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/238)
> Reduce over-firing of newdata event for BAM files

- src/main/BigBedDataSource.js
- src/main/VcfDataSource.js
The next step is to consolidate all this shared logic between data sources.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/239)
> Reduce over-firing in VCF/BigBed sources

- src/main/Alignment.js
- src/main/GA4GHAlignment.js
- src/main/SamRead.js
- src/main/formats/bamTypes.js
- src/test/GA4GHAlignment-test.js
- src/test/SamRead-test.js
First step towards #110
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/249)
> Read mate pair information

- README.md
[David's got our back][1]
[1]: https://david-dm.org/
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/258)
> Add deps-tracking badge

- src/main/GeneTrack.js
- src/main/Interval.js
- src/main/data-canvas.js
- src/test/Interval-test.js
- src/test/components-test.js
I took the opportunity to put a single arrow in each intron/exon:
See #255 
Fixes #59
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/260)
> Migrate GeneTrack from SVG → Canvas

- src/main/DisplayMode.js
- src/main/GeneTrack.js
- src/main/GenomeTrack.js
- src/main/PileupTrack.js
- src/main/data-canvas.js
- src/main/style.js
- src/main/utils.js
- src/test/GenomeTrack-test.js
- src/test/PileupTrack-test.js
- src/test/components-test.js
- types/types.js
See #255 
I factored out some shared code into `RecordingContext` and the styling settings into `style.js`.
This points the way to allowing panning of any track.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/262)
> Migrate GenomeTrack from SVG→canvas

- src/main/LocationTrack.js
- src/main/ScaleTrack.js
- src/main/style.js
Cute little arrows FTW (#250):
see #255.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/276)
> Migrate {Location, Scale}Track from SVG→canvas

- src/main/CoverageTrack.js
- src/main/GeneTrack.js
- src/main/GenomeTrack.js
- src/main/LocationTrack.js
- src/main/PileupTrack.js
- src/main/ScaleTrack.js
- src/main/VariantTrack.js
- src/main/VisualizationWrapper.js
Fixes #270 
I also removed the unused `onRangeChange` handler.
See [this answer][1] on Stack Overflow.
[1]: http://stackoverflow.com/a/19942008/388951
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/282)
> Disable click handlers after drags

- src/main/GenomeTrack.js
Fixes #265 
Not exactly an illuminating fix, but it works :)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/286)
> Lower loose letters a pixel

- src/main/Alignment.js
- src/main/GA4GHAlignment.js
- src/main/PileupCache.js
- src/main/SamRead.js
- src/main/pileuputils.js
- src/test/GA4GHAlignment-test.js
- src/test/PileupCache-test.js
- src/test/SamRead-test.js
Also, don't use jBinary for read name parsing.
Fixes #291
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/296)
> Cache read name and cigar ops

- .flowconfig
- src/main/PileupTrack.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/301)
> Find the clicked read (fixes #293)

- package.json
- scripts/make-mini-d3.sh
- scripts/watch.sh
- src/main/CoverageTrack.js
- src/main/GeneTrack.js
- src/main/LocationTrack.js
- src/main/PileupTrack.js
- src/main/VisualizationWrapper.js
- src/main/d3utils.js
Fixes #275 
587942 pileup.min.js before
475250 pileup.min.js after
→ 112k savings (19%)
Seems like a nice win. What do you guys think of the approach?
@ihodes @armish
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/302)
> Use a mini-d3

- package.json
The main win here is better-formatted error messages.
https://github.com/facebook/flow/releases/tag/v0.17.0
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/304)
> Update to Flow 0.17

- src/main/LocationTrack.js
- src/main/PileupTrack.js
Fixes #180
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/311)
> Show center lines on pileups

- lib/underscore.js
- src/main/CoverageTrack.js
- src/main/types.js
- src/test/CoverageTrack-test.js
fixes #233.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/312)
> Show mismatches in the coverage track

- src/main/types.js
These are left-overs from #312.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/317)
> Drop left-over type definitions

- .gitignore
- package.json
- scripts/build.sh
- scripts/generate-coverage.sh
- scripts/make-mini-d3.sh
- scripts/watch.sh
- src/main/VisualizationWrapper.js
See #275 
This will let other programs (like cycledash) depend on pileup again.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/318)
> Put minid3 in src/lib

- src/main/GeneTrack.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/319)
> Hide off-screen genes

- src/main/PileupTrack.js
Fixes #325 
This winds up being a nice optimization for deep sequences (e.g. RNAseq or WES)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/326)
> Only render alignments which are visible

- src/main/Controls.js
- src/main/types.js
- src/main/utils.js
- src/test/GenomeTrack-test.js
- src/test/utils-test.js
- style/pileup.css
Fixes #332 
This matches IGV and allows for easier copy/pasting.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/340)
> Location Omnibox

- screenshots/test.py
@ihodes this code should look familiar
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/349)
> Update to seltest 1.0.0

- package.json
- scripts/post-code-size.sh
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/347)
> Pull in travis-weigh-in from NPM

- src/main/CoverageTrack.js
Closes #313 
I'll update the screenshots once the sorting PR is in.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/358)
> Make vafThreshold an option

- src/main/CoverageTrack.js
Fixes #374 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/385)
> Show base pair counts for coverage track

- package.json
- src/main/Alignment.js
- src/main/Controls.js
- src/main/CoverageTrack.js
- src/main/Menu.js
- src/main/PileupTrack.js
- src/main/SamRead.js
- src/main/TwoBit.js
- src/main/bai.js
- src/main/bam.js
- src/main/pileuputils.js
- src/main/types.js
- src/main/utils.js
- src/main/vcf.js
- src/test/CoverageTrack-test.js
- src/test/PileupTrack-test.js
- src/test/RecordedRemoteFile.js
- src/test/SamRead-test.js
- src/test/pileuputils-test.js
See their [blog post][1] and [changelog][2].
The most interesting new features are:
* support for `.js.flow` files, which let you distribute Flow libraries.
* The `flow coverage` command, which reports stats on what fraction of expressions are typed (i.e. do not have type `any`).
pileup.js is pretty well-covered by types:
```
$ for x in src/main/*.js; echo $x $(flow coverage $x)
src/main/Alignment.js Covered: 100.00% (6 of 6 expressions)
src/main/BamDataSource.js Covered: 100.00% (293 of 293 expressions)
src/main/BigBed.js Covered: 100.00% (485 of 485 expressions)
src/main/BigBedDataSource.js Covered: 100.00% (233 of 233 expressions)
src/main/ContigInterval.js Covered: 100.00% (272 of 272 expressions)
src/main/Controls.js Covered: 95.59% (217 of 227 expressions)
src/main/CoverageCache.js …
```
> Update to Flow 0.19

- DESIGN.md
- README.md
- ROADMAP.md
@armish this might have been helpful for you last summer! :)
@ihodes would also appreciate a once-over from you.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/402)
> Add more documentation

- package.json
- src/main/RemoteRequest.js
- src/test/RemoteRequest-test.js
* Modified test scripts for faster test compilation
* Added RemoteRequest and tests to support generic http requests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/429)
> Added support for remote requests

- style/pileup.css
Address #434
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/435)
> Resolve load alignment text jump issues

- src/main/sources/GA4GHDataSource.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/453)
> GA4GHDataSource only requests reads not in cache

- src/main/viz/PileupTrack.js
- src/test/viz/PileupTrack-test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/474)
> Hide alignments

- package.json
- src/main/pileup.js
Can be used for update in npm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/467)
> updated version to 0.6.9

- src/test/viz/FeatureTrack-test.js
- src/test/viz/PileupCache-test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/493)
> Fixed async failing FeatureTrack tests

- src/main/sources/BigBedDataSource.js
- src/main/utils.js
- src/main/viz/GeneTrack.js
- src/test/viz/FeatureTrack-test.js
- src/test/viz/GeneTrack-test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/488)
> fixed null gene name

- package.json
- src/main/pileup.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pileup.js/497)
> update to v0.9.10

- src/main/Alignment.js
- src/main/data/gene.js
- src/main/pileup.js
- src/main/sources/BigBedDataSource.js
- src/main/sources/DataSource.js
- src/main/sources/GA4GHGeneSource.js
- src/main/viz/GeneTrack.js
- src/test/data/gene-test.js
- src/test/sources/GA4GHGeneSource-test.js
- src/test/viz/GeneTrack-test.js
- test-data/refSeqGenes.chr17.75000000-75100000.json
Genes can be read from GA4GH features. GA4GH attributes contain exon information.
> Gene Track works with GA4GH Features

- src/main/Controls.js
- src/main/utils.js
- src/test/viz/GenomeTrack-test.js
Slider sets interval to (powers of 2) + 1.
Using the "+", "-", or "Go" buttons sets the slider appropriately to the closest value.
> Add zoom slider

- README.md
- package.json
- src/main/Controls.js
- src/main/pileup.js
- src/main/utils.js
- src/test/components-test.js
Adds the following functionality:
- zoomOut and zoomIn functionality accessible through pileup.js
- saveSvg functionality accessible through pileup.js
> added save svg option

- scripts/watch.sh
- src/main/VisualizationWrapper.js
- src/main/viz/CoverageTrack.js
- src/main/viz/FeatureTrack.js
- src/main/viz/GeneTrack.js
- src/main/viz/GenomeTrack.js
- src/main/viz/GenotypeTrack.js
- src/main/viz/IdiogramTrack.js
- src/main/viz/LocationTrack.js
- src/main/viz/PileupTrack.js
- src/main/viz/ScaleTrack.js
- src/main/viz/VariantTrack.js
findDOMNode, componentWillUpdate, and string refs are deprecated. This PR replaces these deprecated calls.
> replaced deprecated react calls
